# Generated by Django 4.0.2 on 2022-10-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255)),
                ('competition', models.CharField(choices=[('Division 1 League', 'Division 1 League'), ('Division 2 League ', 'Division 2 League'), ('League Cup, Division 1', 'League Cup, Division 1'), ('League Cup, Division 2', 'League Cup, Division 2'), ('Champions League', 'Champions League'), ('Europa League', 'Europa League'), ('Super Cup', 'Super Cup'), ('International Match', 'International Match')], max_length=100, null=True)),
                ('home_ht', models.IntegerField(blank=True)),
                ('home_ft', models.IntegerField(blank=True)),
                ('away_ht', models.IntegerField(blank=True)),
                ('away_ft', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField(blank=True)),
                ('away', models.IntegerField(blank=True)),
                ('draw', models.IntegerField(blank=True)),
                ('gg', models.IntegerField(blank=True)),
                ('ng', models.IntegerField(blank=True)),
                ('home_h1', models.IntegerField(blank=True)),
                ('away_h1', models.IntegerField(blank=True)),
                ('draw_h1', models.IntegerField(blank=True)),
                ('over_2p5', models.IntegerField(blank=True)),
                ('under_2p5', models.IntegerField(blank=True)),
                ('over_3p5', models.IntegerField(blank=True)),
                ('under_3p5', models.IntegerField(blank=True)),
                ('over_4p5', models.IntegerField(blank=True)),
                ('under_4p5', models.IntegerField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.match')),
            ],
        ),
    ]
