# Generated by Django 4.0.2 on 2022-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='away',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
