# Generated by Django 4.0.2 on 2022-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bet_away_alter_bet_away_h1_alter_bet_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
