# Generated by Django 4.0.2 on 2022-11-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_match_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='gg',
            new_name='ft_score',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='ng',
            new_name='ht_score',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='over_2p5',
            new_name='total_away_goals',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='over_3p5',
            new_name='total_goals',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='over_4p5',
            new_name='total_home_goals',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='under_2p5',
            new_name='total_yc',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='under_3p5',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='under_4p5',
        ),
        migrations.AddField(
            model_name='bet',
            name='away_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='away_ht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='competition',
            field=models.CharField(choices=[('Division 1 League', 'Division 1 League'), ('Division 2 League', 'Division 2 League'), ('League Cup, Division 1', 'League Cup, Division 1'), ('League Cup, Division 2', 'League Cup, Division 2'), ('Champions League', 'Champions League'), ('Europa League', 'Europa League'), ('Super Cup', 'Super Cup'), ('International Match', 'International Match')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_ht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='bet',
            name='away_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='main.club'),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='main.club'),
        ),
    ]
