# Generated by Django 4.0.2 on 2022-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_club_rename_gg_bet_ft_score_rename_ng_bet_ht_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='away_cleansheet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_cleansheet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
