# Generated by Django 4.0.2 on 2022-11-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bet_away_cleansheet_bet_home_cleansheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='ft_score',
            new_name='ft_score_away',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='ht_score',
            new_name='ft_score_home',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='total_away_goals',
            new_name='ht_score_away',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='total_home_goals',
            new_name='ht_score_home',
        ),
    ]
