# Generated by Django 4.0.2 on 2022-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_ft_score_bet_ft_score_away_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='away_cleansheet',
            new_name='away_cleansheet_no',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='home_cleansheet',
            new_name='home_cleansheet_no',
        ),
        migrations.AddField(
            model_name='bet',
            name='away_cleansheet_yes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_cleansheet_yes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
