# Generated by Django 4.0.2 on 2022-11-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_ft_score_home_bet_total_yc_over_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='ht_score_away_over',
            new_name='score_away_over',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='ht_score_away_under',
            new_name='score_away_under',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='ht_score_home_over',
            new_name='score_home_over',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='ht_score_home_under',
            new_name='score_home_under',
        ),
    ]
