# Generated by Django 4.0.2 on 2022-11-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_ht_score_away_over_bet_score_away_over_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='score_away_over',
            new_name='score_away_over_no',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='score_away_under',
            new_name='score_away_over_yes',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='score_home_over',
            new_name='score_home_over_no',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='score_home_under',
            new_name='score_home_over_yes',
        ),
    ]
