# Generated by Django 4.0.2 on 2022-11-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_score_away_over_bet_score_away_over_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='total_goals_away_over',
            new_name='total_yc_over_no',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='total_goals_away_under',
            new_name='total_yc_over_yes',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='total_goals_home_over',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='total_goals_home_under',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='total_yc_over',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='total_yc_under',
        ),
    ]
