# Generated by Django 4.0.2 on 2022-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_total_goals_away_over_bet_total_yc_over_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
